### ISSUE TITLE
Check all subpages for missing fonts

### ISSUE THREAD

**Issue by aknutas** [aknutas/doit-website#15]

**Comment by OlliKousa** [comment]
REASON: 
Self-hosted fontset did not include "latin extended" 
TODO: 
1. Change from local hosted to google fonts 
2. Recheck styling to match font weights as intended
+ While at it, add Kalam font for the headers, like in the design document.

**Comment by OlliKousa** [comment]
I've now fixed the fonts on the test server. (https://doittest.parvus.fi/node/23) 

The font-weights were kinda odd in the first place (300 was defined as 400 and so on), so I had to change them in multiple places. I tried to look through it so that everything makes sense, but I might've missed something.

**Comment by OlliKousa** [comment]
The changes are now live

**Comment by aknutas** [comment]
Thanks!
